/**
 * Generated by endpoints-angular-client-generator (version 0.0.1-0)
 * Arguments:
 *   endpoints-angular-client-generator -s -o example -d discovery/jasify-v1.discovery.json -m jasifyEndpoint -p Jas
 */
/*global angular*/
(function (angular) {
    'use strict';
    angular.module('jasifyEndpoint', ['ng']);
}(angular));
