/**
 * Generated by endpoints-angular-client-generator (version 0.0.1-0)
 * Arguments:
 *   endpoints-angular-client-generator -s -o example -d discovery/urlshortener-v1.discovery.json
 */
/*global angular*/
(function (angular) {
    'use strict';
    angular.module('urlshortener.endpoint', ['ng']);
}(angular));
