/**
 * Generated by endpoints-angular-client-generator (version 0.0.1)
 * Arguments:
 *   endpoints-angular-client-generator -s -o example -d discovery/urlshortener-v1.discovery.json
 */
(function(angular) {
  'use strict';
  angular.module('urlshortener.endpoint', ['ng']);
})(angular);
